import Head from "next/head";
import { Inter } from "next/font/google";
import {
  About,
  Contact,
  Footer,
  MainBanner,
  Navbar,
  Project,
  Skill,
} from "@/components";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <div>
      <Head>
        <title>Portofolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/iconL.svg" />
        <link
          href="https://cdnjs.cloudflare.com/ajax/libs/flowbite/1.6.5/flowbite.min.css"
          rel="stylesheet"
        />
      </Head>
      <Navbar type={1} />
      <MainBanner />
      <About />
      <Skill />
      <Project />
      <Contact />
      <Footer />
    </div>
  );
}
