import Head from "next/head";
import { Inter } from "next/font/google";
import Navbar from "@/components/organism/Navbar";
import MainBanner from "@/components/organism/MainBanner";
import About from "@/components/organism/About";
import Skill from "@/components/organism/Skill";
import Project from "@/components/organism/Project";
import Contact from "@/components/organism/Contact";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <div>
      <Head>
        <title>Portofolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <MainBanner />
      <About />
      <Skill />
      <Project />
      <Contact />
    </div>
  );
}
